export const MOCK_BREEDS_PARTIAL = {
  message: {
    african: [],
    bulldog: ['boston', 'english', 'french'],
    sheepdog: ['english', 'shetland'],
  },
  status: 'success',
}

export const FLATTENED_MOCK_BREEDS_PARTIAL = [
  'african',
  'boston bulldog',
  'english bulldog',
  'french bulldog',
  'english sheepdog',
  'shetland sheepdog',
]

export const MOCK_BREEDS_ERROR = {
  status: 'error',
  message: 'No route found for "GET /api/breeds/list/a123" with code: 0',
  code: 404,
}

export const MOCK_BREEDS_FULL = {
  message: {
    affenpinscher: [],
    african: [],
    airedale: [],
    akita: [],
    appenzeller: [],
    basenji: [],
    beagle: [],
    bluetick: [],
    borzoi: [],
    bouvier: [],
    boxer: [],
    brabancon: [],
    briard: [],
    buhund: ['norwegian'],
    bulldog: ['boston', 'english', 'french'],
    bullterrier: ['staffordshire'],
    cairn: [],
    cattledog: ['australian'],
    chihuahua: [],
    chow: [],
    clumber: [],
    cockapoo: [],
    collie: ['border'],
    coonhound: [],
    corgi: ['cardigan'],
    cotondetulear: [],
    dachshund: [],
    dalmatian: [],
    dane: ['great'],
    deerhound: ['scottish'],
    dhole: [],
    dingo: [],
    doberman: [],
    elkhound: ['norwegian'],
    entlebucher: [],
    eskimo: [],
    frise: ['bichon'],
    germanshepherd: [],
    greyhound: ['italian'],
    groenendael: [],
    hound: ['afghan', 'basset', 'blood', 'english', 'ibizan', 'walker'],
    husky: [],
    keeshond: [],
    kelpie: [],
    komondor: [],
    kuvasz: [],
    labrador: [],
    leonberg: [],
    lhasa: [],
    malamute: [],
    malinois: [],
    maltese: [],
    mastiff: ['bull', 'english', 'tibetan'],
    mexicanhairless: [],
    mix: [],
    mountain: ['bernese', 'swiss'],
    newfoundland: [],
    otterhound: [],
    papillon: [],
    pekinese: [],
    pembroke: [],
    pinscher: ['miniature'],
    pitbull: [],
    pointer: ['german', 'germanlonghair'],
    pomeranian: [],
    poodle: ['miniature', 'standard', 'toy'],
    pug: [],
    puggle: [],
    pyrenees: [],
    redbone: [],
    retriever: ['chesapeake', 'curly', 'flatcoated', 'golden'],
    ridgeback: ['rhodesian'],
    rottweiler: [],
    saluki: [],
    samoyed: [],
    schipperke: [],
    schnauzer: ['giant', 'miniature'],
    setter: ['english', 'gordon', 'irish'],
    sheepdog: ['english', 'shetland'],
    shiba: [],
    shihtzu: [],
    spaniel: ['blenheim', 'brittany', 'cocker', 'irish', 'japanese', 'sussex', 'welsh'],
    springer: ['english'],
    stbernard: [],
    terrier: [
      'american',
      'australian',
      'bedlington',
      'border',
      'dandie',
      'fox',
      'irish',
      'kerryblue',
      'lakeland',
      'norfolk',
      'norwich',
      'patterdale',
      'russell',
      'scottish',
      'sealyham',
      'silky',
      'tibetan',
      'toy',
      'westhighland',
      'wheaten',
      'yorkshire',
    ],
    vizsla: [],
    waterdog: ['spanish'],
    weimaraner: [],
    whippet: [],
    wolfhound: ['irish'],
  },
  status: 'success',
}
